add LibraryManagerTest
Papla2016/hh-school-2024-unit-testing pull request #1
Opened 2024-12-18 15:48 UTC by Papla2016

Сделал тесты
А разве проверку на отрицательное количество не надо добавлять в добавление, ведь как он может добавить -1 книгу?

2024-12-19 19:38 UTC, blackoutks requested changes
Обрати еще внимание на форматирование. Где-то есть пробелы после запятых и перед фигурными скобками, а где-то нет. И методы хорошо бы отделять пустой строкой.

Еще покрыты не все ветки условия в `returnBook`. Можешь в идее включить `Branch coverage`, тогда при проверке покрытия это будет видно.

2024-12-19 19:38 UTC, blackoutks commented on src/test/java/ru/hh/school/unittesting/example/LibraryManagerTest.java
> +package ru.hh.school.unittesting.example;
Лучше класть тесты в тот же пакет, что и тестируемый класс. В данном случае это `ru.hh.school.unittesting.homework`. И еще, обычно, пакеты в назыаем полностью маленькими буквами, даже если там несколько слов.

2024-12-19 19:38 UTC, blackoutks commented on src/test/java/ru/hh/school/unittesting/example/LibraryManagerTest.java
> +public class LibraryManagerTest {
В JUnit 5 можно не использовать модификатор доступа перед тестовым классом.

2024-12-19 19:38 UTC, blackoutks commented on src/test/java/ru/hh/school/unittesting/example/LibraryManagerTest.java
> +    );//не должна ли кидаться ошибка, когда добавляется отрицательное количество книг?
Может и должна. Но тут ни в одном методе это не проверяется. И в данный момент этот тест падает, а должно все проходить. В целом, это одна из целей юнит-тестирования - найти какие-то корнер кейсы, которые не были учтены при написании кода. Но в этом задании пишем тесты на то, что есть.

2024-12-20 10:07 UTC, Papla2016 commented
Попробовал `Branch coverage`. На ноутбуке не показывается 4 столбец с полем `Branch, %`. На компьютере он показывается.

2024-12-21 12:27 UTC, blackoutks approved these changes

2024-12-21 12:34 UTC, merged